---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - echo "starting test"
#  - cd roles/world-domination/
  # doing a simple syntax check of the role
  - ansible-playbook roles/world-domination/tests/test.yml -i roles/world-domination/tests/inventory --syntax-check
  # Now, we try to execute the role under test conditions
  - ansible-playbook roles/world-domination/tests/test.yml -i roles/world-domination/tests/inventory 

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  
